// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_AMMOTYPEFB_FBAMMO_H_
#define FLATBUFFERS_GENERATED_AMMOTYPEFB_FBAMMO_H_

#include "flatbuffers/flatbuffers.h"

namespace fbAmmo {

enum FB_AmmoType : int8_t {
  FB_AmmoType_INVALID = 0,
  FB_AmmoType_NONE = 1,
  FB_AmmoType_A_5_56 = 2,
  FB_AmmoType_A_7_62 = 3,
  FB_AmmoType_MIN = FB_AmmoType_INVALID,
  FB_AmmoType_MAX = FB_AmmoType_A_7_62
};

inline const FB_AmmoType (&EnumValuesFB_AmmoType())[4] {
  static const FB_AmmoType values[] = {
    FB_AmmoType_INVALID,
    FB_AmmoType_NONE,
    FB_AmmoType_A_5_56,
    FB_AmmoType_A_7_62
  };
  return values;
}

inline const char * const *EnumNamesFB_AmmoType() {
  static const char * const names[5] = {
    "INVALID",
    "NONE",
    "A_5_56",
    "A_7_62",
    nullptr
  };
  return names;
}

inline const char *EnumNameFB_AmmoType(FB_AmmoType e) {
  if (flatbuffers::IsOutRange(e, FB_AmmoType_INVALID, FB_AmmoType_A_7_62)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFB_AmmoType()[index];
}

}  // namespace fbAmmo

#endif  // FLATBUFFERS_GENERATED_AMMOTYPEFB_FBAMMO_H_
