// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SKILLTYPEFB_FBSKILL_H_
#define FLATBUFFERS_GENERATED_SKILLTYPEFB_FBSKILL_H_

#include "flatbuffers/flatbuffers.h"

namespace fbSkill {

enum FB_SkillType : int8_t {
  FB_SkillType_INVALID = 0,
  /// Combat skills
  FB_SkillType_AUTOMATIC_WEAPONS = 1,
  FB_SkillType_BIG_GUNS = 2,
  FB_SkillType_BRAWLING = 3,
  FB_SkillType_MELEE_COMBAT = 4,
  FB_SkillType_SMALL_ARMS = 5,
  FB_SkillType_SNIPER_RIFLES = 6,
  /// General skills
  FB_SkillType_ANIMAL_WHISPERER = 7,
  FB_SkillType_EXPLOSIVES = 8,
  FB_SkillType_FIRST_AID = 9,
  FB_SkillType_SNEAKY_SHIT = 10,
  FB_SkillType_WEIRD_SCIENCE = 11,
  /// Exploration skills
  FB_SkillType_ARMOR_MODDING = 12,
  FB_SkillType_LOCKPICKING = 13,
  FB_SkillType_NERD_STUFF = 14,
  FB_SkillType_MECHANICS = 15,
  FB_SkillType_SURVIVAL = 16,
  FB_SkillType_TOASTER_REPAIR = 17,
  FB_SkillType_WEAPON_MODDING = 18,
  /// Social skills
  FB_SkillType_BARTER = 19,
  FB_SkillType_HARD_ASS = 20,
  FB_SkillType_KISS_ASS = 21,
  FB_SkillType_LEADERSHIP = 22,
  FB_SkillType_MIN = FB_SkillType_INVALID,
  FB_SkillType_MAX = FB_SkillType_LEADERSHIP
};

inline const FB_SkillType (&EnumValuesFB_SkillType())[23] {
  static const FB_SkillType values[] = {
    FB_SkillType_INVALID,
    FB_SkillType_AUTOMATIC_WEAPONS,
    FB_SkillType_BIG_GUNS,
    FB_SkillType_BRAWLING,
    FB_SkillType_MELEE_COMBAT,
    FB_SkillType_SMALL_ARMS,
    FB_SkillType_SNIPER_RIFLES,
    FB_SkillType_ANIMAL_WHISPERER,
    FB_SkillType_EXPLOSIVES,
    FB_SkillType_FIRST_AID,
    FB_SkillType_SNEAKY_SHIT,
    FB_SkillType_WEIRD_SCIENCE,
    FB_SkillType_ARMOR_MODDING,
    FB_SkillType_LOCKPICKING,
    FB_SkillType_NERD_STUFF,
    FB_SkillType_MECHANICS,
    FB_SkillType_SURVIVAL,
    FB_SkillType_TOASTER_REPAIR,
    FB_SkillType_WEAPON_MODDING,
    FB_SkillType_BARTER,
    FB_SkillType_HARD_ASS,
    FB_SkillType_KISS_ASS,
    FB_SkillType_LEADERSHIP
  };
  return values;
}

inline const char * const *EnumNamesFB_SkillType() {
  static const char * const names[24] = {
    "INVALID",
    "AUTOMATIC_WEAPONS",
    "BIG_GUNS",
    "BRAWLING",
    "MELEE_COMBAT",
    "SMALL_ARMS",
    "SNIPER_RIFLES",
    "ANIMAL_WHISPERER",
    "EXPLOSIVES",
    "FIRST_AID",
    "SNEAKY_SHIT",
    "WEIRD_SCIENCE",
    "ARMOR_MODDING",
    "LOCKPICKING",
    "NERD_STUFF",
    "MECHANICS",
    "SURVIVAL",
    "TOASTER_REPAIR",
    "WEAPON_MODDING",
    "BARTER",
    "HARD_ASS",
    "KISS_ASS",
    "LEADERSHIP",
    nullptr
  };
  return names;
}

inline const char *EnumNameFB_SkillType(FB_SkillType e) {
  if (flatbuffers::IsOutRange(e, FB_SkillType_INVALID, FB_SkillType_LEADERSHIP)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFB_SkillType()[index];
}

}  // namespace fbSkill

#endif  // FLATBUFFERS_GENERATED_SKILLTYPEFB_FBSKILL_H_
