// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WEAPONTYPEFB_FBWEAPON_H_
#define FLATBUFFERS_GENERATED_WEAPONTYPEFB_FBWEAPON_H_

#include "flatbuffers/flatbuffers.h"

namespace fbWeapon {

enum FB_WeaponType : int8_t {
  FB_WeaponType_INVALID = 0,
  FB_WeaponType_AR = 1,
  FB_WeaponType_SMG = 2,
  FB_WeaponType_SEMI_AUTO_PISTOL = 3,
  FB_WeaponType_REVOLVER = 4,
  FB_WeaponType_AUTO_SHOTGUN = 5,
  FB_WeaponType_PUMP_SHOTGUN = 6,
  FB_WeaponType_SNIPER = 7,
  FB_WeaponType_FLAMETHROWER = 8,
  FB_WeaponType_HMG = 9,
  FB_WeaponType_EXPLOSIVE = 10,
  FB_WeaponType_SCIENCE = 11,
  FB_WeaponType_BLADED = 12,
  FB_WeaponType_BLUNT = 13,
  FB_WeaponType_BRAWLING = 14,
  FB_WeaponType_GROUP_ANY = 15,
  FB_WeaponType_MIN = FB_WeaponType_INVALID,
  FB_WeaponType_MAX = FB_WeaponType_GROUP_ANY
};

inline const FB_WeaponType (&EnumValuesFB_WeaponType())[16] {
  static const FB_WeaponType values[] = {
    FB_WeaponType_INVALID,
    FB_WeaponType_AR,
    FB_WeaponType_SMG,
    FB_WeaponType_SEMI_AUTO_PISTOL,
    FB_WeaponType_REVOLVER,
    FB_WeaponType_AUTO_SHOTGUN,
    FB_WeaponType_PUMP_SHOTGUN,
    FB_WeaponType_SNIPER,
    FB_WeaponType_FLAMETHROWER,
    FB_WeaponType_HMG,
    FB_WeaponType_EXPLOSIVE,
    FB_WeaponType_SCIENCE,
    FB_WeaponType_BLADED,
    FB_WeaponType_BLUNT,
    FB_WeaponType_BRAWLING,
    FB_WeaponType_GROUP_ANY
  };
  return values;
}

inline const char * const *EnumNamesFB_WeaponType() {
  static const char * const names[17] = {
    "INVALID",
    "AR",
    "SMG",
    "SEMI_AUTO_PISTOL",
    "REVOLVER",
    "AUTO_SHOTGUN",
    "PUMP_SHOTGUN",
    "SNIPER",
    "FLAMETHROWER",
    "HMG",
    "EXPLOSIVE",
    "SCIENCE",
    "BLADED",
    "BLUNT",
    "BRAWLING",
    "GROUP_ANY",
    nullptr
  };
  return names;
}

inline const char *EnumNameFB_WeaponType(FB_WeaponType e) {
  if (flatbuffers::IsOutRange(e, FB_WeaponType_INVALID, FB_WeaponType_GROUP_ANY)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFB_WeaponType()[index];
}

}  // namespace fbWeapon

#endif  // FLATBUFFERS_GENERATED_WEAPONTYPEFB_FBWEAPON_H_
