// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WEAPONMODELFB_FBWEAPON_H_
#define FLATBUFFERS_GENERATED_WEAPONMODELFB_FBWEAPON_H_

#include "flatbuffers/flatbuffers.h"

namespace fbWeapon {

enum FB_WeaponModel : int16_t {
  FB_WeaponModel_INVALID = 0,
  FB_WeaponModel_AR_KALASH97 = 1,
  FB_WeaponModel_AR_SOCOM = 2,
  FB_WeaponModel_SMG_RIPPER = 3,
  FB_WeaponModel_MIN = FB_WeaponModel_INVALID,
  FB_WeaponModel_MAX = FB_WeaponModel_SMG_RIPPER
};

inline const FB_WeaponModel (&EnumValuesFB_WeaponModel())[4] {
  static const FB_WeaponModel values[] = {
    FB_WeaponModel_INVALID,
    FB_WeaponModel_AR_KALASH97,
    FB_WeaponModel_AR_SOCOM,
    FB_WeaponModel_SMG_RIPPER
  };
  return values;
}

inline const char * const *EnumNamesFB_WeaponModel() {
  static const char * const names[5] = {
    "INVALID",
    "AR_KALASH97",
    "AR_SOCOM",
    "SMG_RIPPER",
    nullptr
  };
  return names;
}

inline const char *EnumNameFB_WeaponModel(FB_WeaponModel e) {
  if (flatbuffers::IsOutRange(e, FB_WeaponModel_INVALID, FB_WeaponModel_SMG_RIPPER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFB_WeaponModel()[index];
}

}  // namespace fbWeapon

#endif  // FLATBUFFERS_GENERATED_WEAPONMODELFB_FBWEAPON_H_
